# Generated by Django 4.1.2 on 2024-01-09 03:44

from django.db import migrations, models
import django.db.models.deletion
import ms_business_central_api.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting_exports', '0001_initial'),
        ('fyle', '0001_initial'),
        ('workspaces', '0002_alter_workspace_ms_business_central_accounts_last_synced_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at')),
                ('accounts_payable_account_id', ms_business_central_api.models.fields.StringNullField(help_text='destination id of accounts payable account', max_length=255, null=True)),
                ('amount', ms_business_central_api.models.fields.FloatNullField(help_text='Amount of the invoice', null=True)),
                ('comment', ms_business_central_api.models.fields.TextNotNullField(help_text='description for the invoice')),
                ('description', ms_business_central_api.models.fields.TextNullField(help_text='description for the invoice', null=True)),
                ('invoice_date', ms_business_central_api.models.fields.CustomDateTimeField(help_text='date of invoice', null=True)),
                ('document_number', ms_business_central_api.models.fields.TextNotNullField(help_text='document number of the invoice')),
                ('accounting_export', models.OneToOneField(help_text='Accounting Export reference', on_delete=django.db.models.deletion.PROTECT, related_name='journal_entry', to='accounting_exports.accountingexport')),
                ('workspace', models.ForeignKey(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'journal_entries',
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLineItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at')),
                ('accounts_payable_account_id', ms_business_central_api.models.fields.StringNullField(help_text='destination id of accounts payable account', max_length=255, null=True)),
                ('amount', ms_business_central_api.models.fields.FloatNullField(help_text='Amount of the invoice', null=True)),
                ('comment', ms_business_central_api.models.fields.TextNotNullField(help_text='description for the invoice')),
                ('description', ms_business_central_api.models.fields.TextNullField(help_text='description for the invoice', null=True)),
                ('invoice_date', ms_business_central_api.models.fields.CustomDateTimeField(help_text='date of invoice', null=True)),
                ('document_number', ms_business_central_api.models.fields.TextNotNullField(help_text='document number of the invoice')),
                ('expense', models.OneToOneField(help_text='Reference to Expense', on_delete=django.db.models.deletion.PROTECT, to='fyle.expense')),
                ('journal_entry', models.ForeignKey(help_text='Journal Entry reference', on_delete=django.db.models.deletion.PROTECT, related_name='journal_entry_lineitems', to='business_central.journalentry')),
                ('workspace', models.ForeignKey(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'journal_entries_lineitems',
            },
        ),
    ]
