# Generated by Django 4.1.2 on 2024-01-11 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_central', '0002_purchaseinvoice_journalentry_employee_account_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='description',
        ),
    ]
