# Generated by Django 4.1.2 on 2024-11-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_central', '0003_journalentrylineitems_dimension_error_log_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentrylineitems',
            name='dimension_success_log',
            field=models.JSONField(help_text='dimension set success response log', null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoicelineitems',
            name='dimension_success_log',
            field=models.JSONField(help_text='dimension set success response log', null=True),
        ),
        migrations.AlterField(
            model_name='journalentrylineitems',
            name='dimensions',
            field=models.JSONField(default=list, help_text='Business Central dimensions'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoicelineitems',
            name='dimensions',
            field=models.JSONField(default=list, help_text='Business Central dimensions'),
        ),
    ]
