# Generated by Django 4.1.2 on 2024-01-11 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_exports', '0001_initial'),
        ('business_central', '0003_remove_purchaseinvoice_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='accounting_export',
            field=models.OneToOneField(help_text='Accounting Export reference', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoice', to='accounting_exports.accountingexport'),
        ),
    ]
