# Generated by Django 4.1.2 on 2024-01-16 04:14

from django.db import migrations
import ms_business_central_api.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('business_central', '0004_alter_purchaseinvoice_accounting_export'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalentry',
            old_name='employee_account_id',
            new_name='account_id',
        ),
        migrations.RenameField(
            model_name='journalentrylineitems',
            old_name='employee_account_id',
            new_name='account_id',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='account_type',
            field=ms_business_central_api.models.fields.StringNullField(help_text='destination id of employee account', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='journalentrylineitems',
            name='account_type',
            field=ms_business_central_api.models.fields.StringNullField(help_text='destination id of employee account', max_length=255, null=True),
        ),
    ]
