# Generated by Django 4.1.2 on 2023-12-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_skipped',
            field=models.BooleanField(default=False, help_text='Expense is skipped or not', null=True),
        ),
    ]
