# Generated by Django 4.1.2 on 2024-05-14 15:50

from django.db import migrations
import ms_business_central_api.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensefilter',
            name='custom_field_type',
            field=ms_business_central_api.models.fields.StringOptionsField(choices=[('SELECT', 'SELECT'), ('NUMBER', 'NUMBER'), ('TEXT', 'TEXT'), ('BOOLEAN', 'BOOLEAN')], default='', help_text='Custom field type', max_length=255, null=True),
        ),
    ]
