# Generated by Django 4.1.2 on 2024-06-14 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0002_alter_expensefilter_custom_field_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='settlement_id',
        ),
    ]
