# Generated by Django 4.1.2 on 2024-02-07 08:24

from django.db import migrations
import ms_business_central_api.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_exports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingexport',
            name='export_url',
            field=ms_business_central_api.models.fields.StringNullField(help_text='Export URL', max_length=255, null=True),
        ),
    ]
