# Generated by Django 4.1.2 on 2024-01-09 03:44

import apps.workspaces.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import ms_business_central_api.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='ms_business_central_accounts_last_synced_at',
            field=ms_business_central_api.models.fields.CustomDateTimeField(help_text='ms business central accounts last synced at time', null=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='onboarding_state',
            field=ms_business_central_api.models.fields.StringOptionsField(choices=[('CONNECTION', 'CONNECTION'), ('COMPANY_SELECTION', 'COMPANY_SELECTION'), ('EXPORT_SETTINGS', 'EXPORT_SETTINGS'), ('IMPORT_SETTINGS', 'IMPORT_SETTINGS'), ('ADVANCED_CONFIGURATION', 'ADVANCED_CONFIGURATION'), ('COMPLETE', 'COMPLETE')], default=apps.workspaces.models.get_default_onboarding_state, help_text='Onboarding status of the workspace', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='LastExportDetail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at datetime')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_exported_at', models.DateTimeField(help_text='Last exported at datetime', null=True)),
                ('export_mode', models.CharField(choices=[('MANUAL', 'MANUAL'), ('AUTO', 'AUTO')], help_text='Mode of the export Auto / Manual', max_length=50, null=True)),
                ('total_accounting_exports_count', models.IntegerField(help_text='Total count of accounting exports exported', null=True)),
                ('successful_accounting_exports_count', models.IntegerField(help_text='count of successful accounting_exports ', null=True)),
                ('failed_accounting_exports_count', models.IntegerField(help_text='count of failed accounting_exports ', null=True)),
                ('workspace', models.OneToOneField(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'last_export_details',
            },
        ),
        migrations.CreateModel(
            name='ImportSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at datetime')),
                ('import_categories', ms_business_central_api.models.fields.BooleanFalseField(default=True, help_text='toggle for import of chart of accounts from Business Central')),
                ('import_vendors_as_merchants', ms_business_central_api.models.fields.BooleanFalseField(default=True, help_text='toggle for import of vendors as merchant from Business Central')),
                ('workspace', models.OneToOneField(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'import_settings',
            },
        ),
        migrations.CreateModel(
            name='FyleCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at datetime')),
                ('refresh_token', ms_business_central_api.models.fields.TextNotNullField(help_text='Fyle refresh token')),
                ('cluster_domain', ms_business_central_api.models.fields.StringNullField(help_text='Fyle cluster domain', max_length=255, null=True)),
                ('workspace', models.OneToOneField(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'fyle_credentials',
            },
        ),
        migrations.CreateModel(
            name='ExportSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at datetime')),
                ('reimbursable_expenses_export_type', ms_business_central_api.models.fields.StringOptionsField(choices=[('PURCHASE_INVOICE', 'PURCHASE_INVOICE'), ('JOURNAL_ENTRY', 'JOURNAL_ENTRY')], default='', help_text='string field with options', max_length=255, null=True)),
                ('default_bank_account_name', ms_business_central_api.models.fields.StringNullField(help_text='Bank account name', max_length=255, null=True)),
                ('default_back_account_id', ms_business_central_api.models.fields.StringNullField(help_text='Bank Account ID', max_length=255, null=True)),
                ('reimbursable_expense_state', ms_business_central_api.models.fields.StringOptionsField(choices=[('PAYMENT_PROCESSING', 'PAYMENT_PROCESSING'), ('PAID', 'PAID')], default='', help_text='string field with options', max_length=255, null=True)),
                ('reimbursable_expense_date', ms_business_central_api.models.fields.StringOptionsField(choices=[('LAST_SPENT_AT', 'last_spent_at'), ('CREATED_AT', 'created_at'), ('SPENT_AT', 'spent_at')], default='', help_text='string field with options', max_length=255, null=True)),
                ('reimbursable_expense_grouped_by', ms_business_central_api.models.fields.StringOptionsField(choices=[('REPORT', 'report_id'), ('EXPENSE', 'expense_id')], default='', help_text='string field with options', max_length=255, null=True)),
                ('credit_card_expense_export_type', ms_business_central_api.models.fields.StringOptionsField(choices=[('JOURNAL_ENTRY', 'JOURNAL_ENTRY')], default='', help_text='string field with options', max_length=255, null=True)),
                ('credit_card_expense_state', ms_business_central_api.models.fields.StringOptionsField(choices=[('APPROVED', 'APPROVED'), ('PAYMENT_PROCESSING', 'PAYMENT_PROCESSING'), ('PAID', 'PAID')], default='', help_text='string field with options', max_length=255, null=True)),
                ('default_reimbursable_account_name', ms_business_central_api.models.fields.StringNullField(help_text='Reimbursable account name', max_length=255, null=True)),
                ('default_reimbursable_account_id', ms_business_central_api.models.fields.StringNullField(help_text='Reimbursable Account ID', max_length=255, null=True)),
                ('default_ccc_credit_card_account_name', ms_business_central_api.models.fields.StringNullField(help_text='CCC Credit card account name', max_length=255, null=True)),
                ('default_ccc_credit_card_account_id', ms_business_central_api.models.fields.StringNullField(help_text='CCC Credit Card Account ID', max_length=255, null=True)),
                ('default_reimbursable_credit_card_account_name', ms_business_central_api.models.fields.StringNullField(help_text='Reimbursable Credit card account name', max_length=255, null=True)),
                ('default_reimbursable_credit_card_account_id', ms_business_central_api.models.fields.StringNullField(help_text='Reimbursable Credit card account name', max_length=255, null=True)),
                ('credit_card_expense_grouped_by', ms_business_central_api.models.fields.StringOptionsField(choices=[('REPORT', 'report_id'), ('EXPENSE', 'expense_id')], default='', help_text='string field with options', max_length=255, null=True)),
                ('credit_card_expense_date', ms_business_central_api.models.fields.StringOptionsField(choices=[('LAST_SPENT_AT', 'last_spent_at'), ('POSTED_AT', 'posted_at'), ('CREATED_AT', 'created_at')], default='', help_text='string field with options', max_length=255, null=True)),
                ('default_vendor_name', ms_business_central_api.models.fields.StringNullField(help_text='default Vendor Name', max_length=255, null=True)),
                ('default_vendor_id', ms_business_central_api.models.fields.StringNullField(help_text='default Vendor Id', max_length=255, null=True)),
                ('auto_map_employees', ms_business_central_api.models.fields.BooleanTrueField(default=True, help_text='Auto map employees')),
                ('default_journal_entry_folder_id', ms_business_central_api.models.fields.StringNullField(help_text='default Fyle journal entry id', max_length=255, null=True)),
                ('workspace', models.OneToOneField(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'export_settings',
            },
        ),
        migrations.CreateModel(
            name='BusinessCentralCredentials',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at datetime')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('refresh_token', models.TextField(help_text='Stores Business Central refresh token', null=True)),
                ('is_expired', models.BooleanField(default=False, help_text='Business Central token expiry flag')),
                ('workspace', models.OneToOneField(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'business_central_credentials',
            },
        ),
        migrations.CreateModel(
            name='AdvancedSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at datetime')),
                ('expense_memo_structure', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), help_text='Array of fields in memo', null=True, size=None)),
                ('schedule_is_enabled', ms_business_central_api.models.fields.BooleanFalseField(default=True, help_text='Boolean to check if schedule is enabled')),
                ('start_datetime', ms_business_central_api.models.fields.CustomDateTimeField(help_text='Schedule start date and time', null=True)),
                ('schedule_id', ms_business_central_api.models.fields.StringNullField(help_text='Schedule id', max_length=255, null=True)),
                ('interval_hours', ms_business_central_api.models.fields.IntegerNullField(help_text='Interval in hours', null=True)),
                ('emails_selected', ms_business_central_api.models.fields.CustomJsonField(default=list, help_text='Emails Selected For Email Notification', null=True)),
                ('emails_added', ms_business_central_api.models.fields.CustomJsonField(default=list, help_text='Emails Selected For Email Notification', null=True)),
                ('auto_create_vendor', ms_business_central_api.models.fields.BooleanFalseField(default=True, help_text='Auto create vendor')),
                ('workspace', models.OneToOneField(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'advanced_settings',
            },
        ),
    ]
