# Generated by Django 4.1.2 on 2024-01-11 10:18

from django.db import migrations
import ms_business_central_api.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_alter_workspace_ms_business_central_accounts_last_synced_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exportsetting',
            old_name='default_journal_entry_folder_id',
            new_name='journal_entry_folder_id',
        ),
        migrations.RemoveField(
            model_name='exportsetting',
            name='auto_map_employees',
        ),
        migrations.RemoveField(
            model_name='exportsetting',
            name='default_ccc_credit_card_account_id',
        ),
        migrations.RemoveField(
            model_name='exportsetting',
            name='default_ccc_credit_card_account_name',
        ),
        migrations.RemoveField(
            model_name='exportsetting',
            name='default_reimbursable_account_id',
        ),
        migrations.RemoveField(
            model_name='exportsetting',
            name='default_reimbursable_account_name',
        ),
        migrations.RemoveField(
            model_name='exportsetting',
            name='default_reimbursable_credit_card_account_id',
        ),
        migrations.RemoveField(
            model_name='exportsetting',
            name='default_reimbursable_credit_card_account_name',
        ),
        migrations.AddField(
            model_name='exportsetting',
            name='emoloyee_mapping',
            field=ms_business_central_api.models.fields.StringNullField(help_text='Employee Mapping', max_length=255, null=True),
        ),
    ]
