# Generated by Django 4.1.2 on 2024-02-26 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_q', '0014_schedule_cluster'),
        ('workspaces', '0002_alter_workspace_ms_business_central_accounts_last_synced_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancedsetting',
            name='schedule_id',
        ),
        migrations.AddField(
            model_name='advancedsetting',
            name='schedule',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='django_q.schedule'),
        ),
    ]
