# Generated by Django 4.1.2 on 2024-11-25 09:47

import apps.workspaces.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_remove_advancedsetting_schedule_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importsetting',
            name='charts_of_accounts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=apps.workspaces.models.get_default_chart_of_accounts, help_text='list of chart of account types to be imported into Fyle', size=None),
        ),
    ]
