# Generated by Django 4.1.2 on 2024-01-16 04:14

from django.db import migrations
import ms_business_central_api.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_rename_default_journal_entry_folder_id_exportsetting_journal_entry_folder_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportsetting',
            name='import_vendors_as_merchants',
            field=ms_business_central_api.models.fields.BooleanFalseField(default=True, help_text='toggle for import of vendors as merchant from Business Central'),
        ),
        migrations.AddField(
            model_name='exportsetting',
            name='name_in_journal_entry',
            field=ms_business_central_api.models.fields.StringOptionsField(choices=[('EMPLOYEE', 'EMPLOYEE'), ('MERCHANT', 'MERCHANT')], default='', help_text='string field with options', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exportsetting',
            name='emoloyee_mapping',
            field=ms_business_central_api.models.fields.StringOptionsField(choices=[('EMPLOYEE', 'EMPLOYEE'), ('VENDOR', 'VENDOR')], default='', help_text='string field with options', max_length=255, null=True),
        ),
    ]
