# Generated by Django 4.1.2 on 2024-01-16 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_exportsetting_import_vendors_as_merchants_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exportsetting',
            old_name='emoloyee_mapping',
            new_name='employee_mapping',
        ),
    ]
