# Generated by Django 4.1.2 on 2024-01-17 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_rename_emoloyee_mapping_exportsetting_employee_mapping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exportsetting',
            old_name='employee_mapping',
            new_name='employee_field_mapping',
        ),
    ]
