# Generated by Django 4.1.2 on 2024-01-16 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_rename_emoloyee_mapping_exportsetting_employee_mapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importsetting',
            name='workspace',
            field=models.OneToOneField(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, related_name='import_settings', to='workspaces.workspace'),
        ),
    ]
