# Generated by Django 4.1.2 on 2024-12-12 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_exportsetting_default_ccc_bank_account_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exportsetting',
            old_name='default_CCC_bank_account_id',
            new_name='default_ccc_bank_account_id',
        ),
        migrations.RenameField(
            model_name='exportsetting',
            old_name='default_CCC_bank_account_name',
            new_name='default_ccc_bank_account_name',
        ),
    ]
