# Generated by Django 4.1.2 on 2024-01-17 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0006_alter_importsetting_workspace'),
        ('workspaces', '0006_rename_employee_mapping_exportsetting_employee_field_mapping'),
    ]

    operations = [
    ]
