# Generated by Django 4.1.2 on 2024-12-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0006_rename_default_ccc_bank_account_id_exportsetting_default_ccc_bank_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacesuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Created at datetime', null=True),
        ),
        migrations.AddField(
            model_name='workspacesuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Updated at datetime', null=True),
        ),
    ]
