# Generated by Django 4.1.2 on 2024-01-18 13:13

from django.db import migrations
import ms_business_central_api.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0007_merge_20240117_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportsetting',
            name='reimbursable_expense_date',
            field=ms_business_central_api.models.fields.StringOptionsField(choices=[('LAST_SPENT_AT', 'last_spent_at'), ('CURRENT_DATE', 'current_date'), ('SPENT_AT', 'spent_at')], default='', help_text='string field with options', max_length=255, null=True),
        ),
    ]
