# Generated by Django 4.1.2 on 2024-01-18 11:37

from django.db import migrations
import ms_business_central_api.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0007_merge_20240117_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportsetting',
            name='import_vendors_as_merchants',
        ),
        migrations.AddField(
            model_name='exportsetting',
            name='auto_map_employees',
            field=ms_business_central_api.models.fields.StringOptionsField(choices=[('NAME', 'NAME'), ('EMAIL', 'EMAIL')], default='', help_text='string field with options', max_length=255, null=True),
        ),
    ]
