# Generated by Django 4.1.2 on 2024-12-23 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0007_workspacesuser_created_at_workspacesuser_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspacesuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='workspacesuser',
            name='updated_at',
        ),
    ]
