# Generated by Django 4.1.2 on 2024-12-23 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0008_remove_workspacesuser_created_at_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE workspaces_user
                ADD COLUMN created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
            """,
            reverse_sql="""
                ALTER TABLE workspaces_user
                DROP COLUMN created_at;
            """,
        ),
    ]
