# Generated by Django 4.1.2 on 2024-01-18 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0008_remove_exportsetting_import_vendors_as_merchants_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exportsetting',
            old_name='default_back_account_id',
            new_name='default_bank_account_id',
        ),
    ]
