# Generated by Django 4.1.2 on 2024-01-23 07:37

from django.db import migrations
import ms_business_central_api.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0009_rename_default_back_account_id_exportsetting_default_bank_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportsetting',
            name='credit_card_expense_date',
            field=ms_business_central_api.models.fields.StringOptionsField(choices=[('LAST_SPENT_AT', 'last_spent_at'), ('POSTED_AT', 'posted_at'), ('CURRENT_DATE', 'current_date'), ('SPENT_AT', 'spent_at')], default='', help_text='string field with options', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exportsetting',
            name='reimbursable_expense_date',
            field=ms_business_central_api.models.fields.StringOptionsField(choices=[('LAST_SPENT_AT', 'last_spent_at'), ('CURRENT_DATE', 'current_date'), ('SPENT_AT', 'spent_at')], default='', help_text='string field with options', max_length=255, null=True),
        ),
    ]
