name: Commit to Release Branch

on:
  schedule:
    # Run every Friday at 11:30 AM UTC (5:00 PM IST)
    - cron: '59 4 * * *'

jobs:
  commit-to-release-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set release branch name
      run: echo "release_branch=ms-business-central_release_$(date +%Y_%m_%d)" >> $GITHUB_ENV

    - name: Commit changes and Push
      run: |
        git config --global user.email "integrations@fylehq.com"
        git config --global user.name "GitHub Actions"
        git checkout ${{env.release_branch}}
        git add .
        git pull origin ${{ env.release_branch }}
        git commit --allow-empty -m "Release branch creation commit"
        git push origin ${{ env.release_branch }}
